version: '3'

services:
  master:
    image: itzg/elasticsearch:2.4.0
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
  data:
    image: itzg/elasticsearch:2.4.0
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 60s
  gateway:
    image: itzg/elasticsearch:2.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TYPE: GATEWAY
      UNICAST_HOSTS: master
  kibana:
    image: kibana:4.6.4
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://gateway:9200
  todoapp:
    image: fischermatte/todo-app:0.0.1-SNAPSHOT
    container_name: todoapp
    ports:
      - 8080:8080
    environment:
      - spring.data.elasticsearch.cluster-name=elasticsearch
      - spring.data.elasticsearch.cluster-nodes=gateway:9300
    depends_on:
      - gateway
